--Generate Pega Database

CREATE DATABASE "PRPC"
    WITH
    OWNER = pgadmin
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_India.1252'
    LC_CTYPE = 'English_India.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE "PRPC" TO PUBLIC;
GRANT ALL ON DATABASE "PRPC" TO pgadmin WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO pgadmin WITH GRANT OPTION;


--Generate Pega Data Schema

CREATE SCHEMA IF NOT EXISTS pegadata AUTHORIZATION postgres;
GRANT ALL ON SCHEMA pegadata TO postgres WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA pegadata GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;


--Generate Pega Rule Schema

CREATE SCHEMA IF NOT EXISTS pegarules AUTHORIZATION postgres;
GRANT ALL ON SCHEMA pegarules TO postgres WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA pegarules GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;